#!/usr/bin/env perl

use strict;
use warnings;

use File::Slurp;
use Data::Dumper;
use POSIX qw(strftime);

my $sender = $ENV{'SMS_1_NUMBER'};
my $message = $ENV{'SMS_1_TEXT'};

my $time = strftime "%a %b %e %H:%M:%S %Y", localtime;

my $log = sprintf("[%s]: %s %s\n", $time, $sender, $message);

write_file( '/var/log/sms.log', { append => 1 }, $log) ;

my $reply;

if ($message eq "ping") {
    $reply = "pong";
} elsif ($message eq "status") {
    $reply = `uptime`;
} elsif ($message =~ m/^cmd\:\s?(.*?)$/isg) {
    my $cmd = $1;
    $reply = `$cmd` if $cmd;
} else {
}

$reply =~ s{\"}{\\\"}sg if $reply;

write_file( '/var/log/sms.log', { append => 1 }, $reply . "\n") if $reply;

system( "gammu-smsd-inject", "TEXT", $sender, "-text", qq{"$reply"} ) if $reply;

exit 0;
